name = "contained"
description = "manage contained python repo"
working_dir = "~/py_projects/contained/"   # 
[[tabs]]
name = "IDE"
[[tabs.panes]]
label ="nvim"
command ="nvim README.md"
[[tabs.panes]]
label = "venv"
command ="herdr pane resize --direction down --amount 0.3 --current&&source .venv/bin/activate"
split ="down"
