name = "herdr plus proj"
description = "edit proj"
working_dir = "~/.config/herdr/plugins/config/cloudmanic.herdr-plus/projects/"   # 
[[tabs]]
name = "h plus pr"
[[tabs.panes]]
label ="nv h plus pr"
command ="nvim $PWD"
[[tabs.panes]]
label = "bash h plus"
command ="herdr pane resize --direction down --amount 0.3 --current&&ls -alt"
split ="down"
