name = "silverbullet"
description = "Todo and more"
working_dir = "~/send_to_silverbullet/"   # 
[[tabs]]
name = "sb tab"
[[tabs.panes]]
label ="nv sb"
command ="nvim $PWD"
[[tabs.panes]]
label = "bash sb"
command ="herdr pane resize --direction down --amount 0.3 --current&&ls -alt"
split ="down"
